---
title: "Lab 4.6 Logistic regression, LDA, QDA and KNN"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 4.6.1 The stock market data
```{r}
library(ISLR)
```
```{r}
names(Smarket)
```
```{r}
summary(Smarket)
```
```{r}
pairs(Smarket)
```
```{r}
cor(Smarket[, -9])
```

```{r}
with(data = Smarket, plot (Volume))
```

## 4.6.2 Logistic regression
```{r}
glm.fit <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume, data=Smarket,
               family=binomial)
summary(glm.fit)
```
```{r}
coef(glm.fit)
```
```{r}
summary(glm.fit)$coef
```

```{r}
summary(glm.fit)$coef[, 4]
```

```{r}
glm.probs <- predict(glm.fit, type="response")
glm.probs[1:10]
```
```{r}
with(data=Smarket, contrasts(Direction))
```

```{r}
glm.pred <- rep("Down", 1250)
glm.pred[glm.probs > 0.5] = "Up"
```
```{r}
with(data=Smarket, table(glm.pred, Direction))
```

```{r}
(507 + 145)/1250
```

```{r}
with(data=Smarket, mean(glm.pred==Direction))
```

```{r}
train <- (Smarket$Year < 2005)
Smarket.2005 <- Smarket[!train, ]
dim(Smarket.2005)
```
```{r}
Direction.2005 <- Smarket$Direction[!train]
```

```{r}
glm.fit <- glm(Direction~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume, data=Smarket,
               family=binomial, subset=train)
glm.probs <- predict(glm.fit, Smarket.2005, type="response")
```

```{r}
glm.pred <- rep("Down", 252)
glm.pred[glm.probs > 0.5] = "Up"
table(glm.pred, Direction.2005)
```

```{r}
mean(glm.pred == Direction.2005)
```
```{r}
glm.fit <- glm(Direction~ Lag1 + Lag2, data=Smarket,
               family=binomial, subset=train)
glm.probs <- predict(glm.fit, Smarket.2005, type="response")
```
```{r}
glm.pred <- rep("Down", 252)
glm.pred[glm.probs > 0.5] = "Up"
table(glm.pred, Direction.2005)
```
```{r}
mean(glm.pred == Direction.2005)
```
```{r}
predict(glm.fit, newdata = data.frame(Lag1=c(1.2, 1.5), Lag2=c(1.1, -0.8)), type = "response")
```

