---
title: "Lab 9.6 SVM with multipe classes"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 9.6.4 SVM with multipe classes
```{r}
set.seed(1)
x <- matrix(rnorm(200*2), ncol=2)
x[1:100,] = x[1:10,] + 2
x[101:150,] = x[101:150,] - 2
y = c(rep(1, 150), rep(2, 50))

set.seed(1)
x <- rbind(x, matrix(rnorm(50*2), ncol = 2))
y <- c(y, rep(0, 50))
x[y==0, 2] =x[y==0, 2] + 2
dat <- data.frame(x=x, y=as.factor(y))
```

```{r}
par(mfrow=c(1,1))
plot(x, col=(y + 1))
```
```{r}
library(e1071)
svmfit <- svm(y ~., data=dat, kernel="radial", cost=10, gamma=1)
plot(svmfit, dat)
```
## 9.6.5 Application to gene expression data
```{r}
library(ISLR)
names(Khan)
```
```{r}
dim(Khan$xtrain)
```
```{r}
dim(Khan$xtest)
```
```{r}
table(Khan$ytrain)
```
```{r}
table(Khan$ytest)
```
```{r}
dat <- data.frame(x=Khan$xtrain, y=as.factor(Khan$ytrain))
out <- svm(y ~., data=dat, kernel="linear", cost=10)
summary(out)
```
```{r}
table(out$fitted, dat$y)
```
```{r}
# on test data set
dat.te <- data.frame(x=Khan$xtest, y=as.factor(Khan$ytest))
pred.te <- predict(out, newdata = dat.te)
table(pred.te, dat.te$y)
```

