---
title: "Lab 10.5 Clustering"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 10.5 lab 2 : clustering
### 10.5.1 K-means clustering
```{r}
set.seed(2)
x <- matrix(rnorm(50*2), ncol=2)
x[1:25, 1] = x[1:25, 1] + 3
x[1:25, 2] = x[1:25, 2] - 4
```
```{r}
km.out <- kmeans(x, 2, nstart = 20)
km.out$cluster
```
```{r}
plot(x, col=(km.out$cluster + 1), 
     main = "K-Means Clustering Results, K=2", 
     xlab = "", pch=20, cex=2)
```
```{r}
set.seed(4)
km.out <- kmeans(x, 3, nstart = 20)
km.out
```
```{r}
set.seed(3)
km.out <- kmeans(x, 3, nstart = 1)
km.out$tot.withinss
```
### 10.5.2 Hiearchical clustering
```{r}
hc.complete <- hclust(dist(x), method = "complete")
```
```{r}
hc.average <- hclust(dist(x), method = "average")
hc.single <- hclust(dist(x), method = "single")
```
```{r}
par(mfrow=c(1, 3))
plot(hc.complete, main = "Complete Linkage", xlab = "", sub = "", cex=0.9)
plot(hc.average, main = "Average Linkage", xlab = "", sub = "", cex=0.9)
plot(hc.single, main = "Single Linkage", xlab = "", sub = "", cex=0.9)
```
```{r}
cutree(hc.complete, 2)
```
```{r}
cutree(hc.average, 2)
```
```{r}
cutree(hc.single, 4)
```
### scale variables
```{r}
xsc <- scale(x)
plot(hclust(dist(xsc), method = "complete"), main="Hierarchical Clustering with scaled features")
```
### Correlation based distance
```{r}
x <- matrix(rnorm(30*3), ncol = 3)
dd <- as.dist(1-cor(t(x)))
plot(hclust(dd, method = "complete"), main="Complete Linkage with Correlation-Based Distance", xlab="", sub="")
```

