---
title: "iris with mlr3"
output: html_document
date: "2022-11-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## first example of mlr3 pipeline 
## working on iris data
```{r}
library(mlr3verse)
library(mlr3learners)

lgr::get_logger("mlr3")$set_threshold("warn")
```

## Creating tasks and learners
```{r}
task = as_task_classif(iris, target = "Species")
task = mlr_tasks$get("iris")
task = tsk("iris")

```
```{r}
# print task
print(task)
```
```{r}
# create learner from dictionary of mlr3learners
learner_lda = mlr_learners$get("classif.lda")
```

```{r}
print(learner_lda)
```
## Train and predict
```{r}
# train learner on subset of task
set.seed(2022)
n = nrow(iris)
train_index <- sample(n, floor(0.7 * n))
test_index <- setdiff(1:n, train_index)
learner_lda$train(task, row_ids = train_index)
```

```{r}
# this is what the decision tree looks like
print(learner_lda$model)
```
```{r}
# predict using observations from task
prediction = learner_lda$predict(task, row_ids = train_index )
print(prediction)
```
```{r}
# predict using "new" observations from an external data.frame
prediction = learner_lda$predict_newdata(newdata = iris[test_index, ])
print(prediction)
```
## Evaluation

```{r}
scores = prediction$score(msr("classif.acc"))
print(scores)
```
```{r}
scores = prediction$score(msrs(c("classif.acc", "classif.ce")))
print(scores)
```
```{r}
cm = prediction$confusion
print(cm)
```

